[package]
name = "crab_call"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
anyhow = "1.0.99"
thiserror = "2.0.16"
tracing = "0.1.41"
cpal = "0.16.0"
ringbuf = "0.4.8"